// This file was autogenerated by ../../third_party/closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('gamebuilder.js', ['gamebuilder'], []);
goog.addDependency('games/chess/chess.js', ['gamebuilder.games.chess'], ['gamebuilder.games']);
goog.addDependency('games/chess/fen.js', ['gamebuilder.games.chess.FEN'], ['gamebuilder.games.chess', 'gamebuilder.games.chess.ui']);
goog.addDependency('games/chess/theme.js', ['gamebuilder.games.chess.theme'], ['gamebuilder.games.chess']);
goog.addDependency('games/chess/ui.js', ['gamebuilder.games.chess.ui'], ['gamebuilder.games.chess', 'gamebuilder.games.chess.theme', 'gamebuilder.util']);
goog.addDependency('games/games.js', ['gamebuilder.games'], ['gamebuilder.util']);
goog.addDependency('games/go/go.js', ['gamebuilder.games.go'], ['gamebuilder.games']);
goog.addDependency('net/net.js', ['gamebuilder.net'], []);
goog.addDependency('testing/testing.js', ['gamebuilder.testing'], []);
goog.addDependency('util/util.js', ['gamebuilder.util'], []);
